spring:
  config:
    activate:
      on-profile: development

  application:
    name: cefetsis dev-profile
  
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hbernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
