version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      
    ports:
      - 5432:5432
      
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
